# Generated by Django 2.2.7 on 2020-02-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='current_user',
        ),
    ]
