# Generated by Django 3.0.3 on 2020-02-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cart',
            new_name='cart_items',
        ),
    ]
