# Generated by Django 3.0.3 on 2020-02-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart_items',
        ),
    ]
