# Generated by Django 3.0.3 on 2020-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_current_user'),
        ('user', '0005_remove_profile_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_items',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
