# Generated by Django 2.2.7 on 2020-03-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
