# Generated by Django 2.2.7 on 2020-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_item_image'),
        ('user', '0009_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('ordered_items', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(to='user.History'),
        ),
    ]
