# Generated by Django 2.2.7 on 2020-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_item_image'),
        ('user', '0010_auto_20200314_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='history',
            name='ordered_items',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
