# Generated by Django 2.2.7 on 2020-03-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
